version: '3.8'

services:
  zerotier:
    build: .
    image: ghcr.io/schmidt-software/zerotier-controller:latest
    labels:
      - "com.docker.compose.project="    
    ports:
      - "9993:9993/udp"
    volumes:
      - zerotier_data:/var/lib/zerotier-one
    deploy:
      restart_policy:
        condition: any

volumes:
  zerotier_data:
    driver: local
